//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalMaalayak
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public int Id { get; set; }
        public string NIC { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> StarId { get; set; }
        public Nullable<int> CapptId { get; set; }
        public string Job { get; set; }
    
        public virtual Cast Cast { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Star Star { get; set; }


    }
}
